name: Publish Telescope Docker image for Private Testnet
on:
  push:
    branches:
      - develop
jobs:
  push_to_registry:
    name: Push Docker image for Private Testnet to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup variables
        id: variables
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./projects/main/Dockerfile
          push: true
          tags: |
            ghcr.io/cauchye/telescope:test
      - name: Create GitHub dispatch event
        run: |
          curl --request POST 'https://api.github.com/repos/UnUniFi/utils/dispatches' \
          --header 'Authorization: Bearer ${{secrets.REPO_GITHUB_ACCESS_TOKEN}}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "event_type": "repository-telescope-new-release-for-private-testnet"
          }'
